export ZSH="/home/kkantor/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(git aws)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim

#export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
#export LIBGL_ALWAYS_INDIRECT=1
PATH=$PATH:~/code/tools/maven/maven-current/bin:~/.local/bin/:/usr/local/go/bin:~/go/bin:~/.cargo/bin
alias python="python3"
alias pip="pip3"

alias diddy="ssh diddy"
alias startpy=". ./venv/bin/activate"
alias endpy="deactivate"

function sshagent () {
	eval ssh-agent $SHELL
}
